/**
 * Placeholder overwritten by scripts/restore-admin-ts.mjs before tsc.
 * Do not edit this file by hand on main until restore lands the full routes.
 */
import { Router } from 'express'
import { requireAuth, requireAdmin } from '../auth.js'

const router = Router()
router.use(requireAuth)
router.use(requireAdmin)
export default router
